### ISSUE TITLE
Add support for dynamic titles in TextSegments

### ISSUE THREAD

**Issue by dregatos** [nedap/Segnify#16]
**Describe the feature**

In order to implement this [feature request](https://app.zenhub.com/workspaces/healthcare-mobile-5968d1701fd83f7d4fdfc0e8/issues/nedap/dossier-ios/817) in Dossier, we need to do some modifications in the Segnify framework. 

Right now, the framework doesn't support dynamic text section titles because they are specified as `rawValues` of an enum, the `ProfileSection`.

<img width="500" alt="image_name" src="https://images.zenhubusercontent.com/59cb5b65b0222d5de4794cd4/57977ab9-2673-4108-9120-b1b1614e32c1">

**Rules/Acceptance criteria**
* R1: Add a new parameter to the initializer `title: String`. @barthopster, is it possible to remove the `ProfileSection` parameter?
* R2: Remove the `NSLocalizedString`. The host app should be responsible to provide the localized string.

**API**
APIs it depends on

**Design**
Mock, or screens if available

**Dependencies**
Depends on other features

**Additional context**

- [ ] **Is the issue ready to start development?** [DoR](https://github.com/nedap/healthcare-mobile/wiki/DoR)

**Comment by dregatos** [comment]
Hey @barthopster,

Do you have time to take a look at this?

**Comment by barthopster** [comment]
I will look into this tomorrow.

**Comment by barthopster** [comment]
Hey @dregatos, this doesn't need any changes in Segnify. `ProfileTextSegment` is part of the Dossier app, not of Segnify.

It's a subclass of `TextSegment`, a Segnify component, and has already the `public convenience init(text: String?, configuration: SegmentProtocol?)` initialiser. That means that you can make all the necessary changes in Dossier 👍.

**Comment by dregatos** [comment]
Oh great!! Then I'll fix it in Dossier. Thx!
